### ISSUE TITLE
mr.bob versions?

### ISSUE THREAD

**Issue by sunew** [domenkozar/mr.bob#78]
Hi - I'm getting a bit confused about the versions of mr.bob. 

In pypi there are two modules: mr.bob and mr.bob2.
The mr.bob2 latest version is 0.2.3, but there is no changelog for that, and i cannot see any tags matching the 0.2.x line here in this git repo.

Is this repo the place where mr.bob development takes place? Where is the 0.2.x line?

Kind regards, and thank you for all the good work!
Sune

**Comment by domenkozar** [comment]
`mr.bob2` is not something I uploaded, it's owned by someone else.
